version: "3"
name: jasmin-mongo
services:
  configuration:
    image: blackorder/jasmin-mongo-configuration
    restart: always
    networks:
      - jasmin-core_jasmin_subnet
      - mongo-cluster_cluster_subnet
    environment:
      JASMIN_CLI_HOST: ${JASMIN_CLI_HOST:-jasmin}
      JASMIN_CLI_PORT: ${JASMIN_CLI_PORT:-8990}
      JASMIN_CLI_TIMEOUT: ${JASMIN_CLI_TIMEOUT:-30}
      JASMIN_CLI_AUTH: ${JASMIN_CLI_AUTH:-True}
      JASMIN_CLI_USERNAME: ${JASMIN_CLI_USERNAME:-jcliadmin}
      JASMIN_CLI_PASSWORD: ${JASMIN_CLI_PASSWORD:-jclipwd}
      JASMIN_CLI_STANDARD_PROMPT: ${JASMIN_CLI_STANDARD_PROMPT}
      JASMIN_CLI_INTERACTIVE_PROMPT: ${JASMIN_CLI_INTERACTIVE_PROMPT}
      MONGO_CONNECTION_STRING: mongodb://${MONGODB_USERNAME:?err}:${MONGODB_PASSWORD:?err}@${MONGODB_CLUSTER_HOSTS:?err}/?authSource=admin&replicaSet=rs
      MONGO_CONFIGURATION_DATABASE: ${MONGO_CONFIGURATION_DATABASE:-configs}
      SYNC_CURRENT_FIRST: ${SYNC_CURRENT_FIRST:-True}
      JASMIN_MONGO_CONFIGURATION_LOG_PATH: ${JASMIN_MONGO_CONFIGURATION_LOG_PATH:-/var/log/jasmin/}
      JASMIN_MONGO_CONFIGURATION_LOG_LEVEL: ${JASMIN_MONGO_CONFIGURATION_LOG_LEVEL:-INFO}

  logger:
    image: blackorder/jasmin-mongo-logger
    restart: always
    networks:
      - jasmin-core_rabbitmq_subnet
      - mongo-cluster_cluster_subnet
    environment:
      AMQP_BROKER_HOST: ${AMQP_BROKER_HOST:-rabbit-mq}
      AMQP_BROKER_PORT: ${AMQP_BROKER_PORT:-5672}
      MONGO_CONNECTION_STRING: mongodb://${MONGODB_USERNAME:?err}:${MONGODB_PASSWORD:?err}@${MONGODB_CLUSTER_HOSTS:?err}/?authSource=admin&replicaSet=rs
      MONGO_LOGGER_DATABASE: ${MONGO_LOGGER_DATABASE:-logger}
      MONGO_LOGGER_COLLECTION: ${MONGO_LOGGER_COLLECTION:-sms_log}
      JASMIN_MONGO_LOGGER_LOG_PATH: ${JASMIN_MONGO_LOGGER_LOG_PATH:-/var/log/jasmin/}
      JASMIN_MONGO_LOGGER_LOG_LEVEL: ${JASMIN_MONGO_LOGGER_LOG_LEVEL:-INFO}

networks:
  # https://github.com/BlackOrder/jasmin-core-docker-service
  jasmin-core_jasmin_subnet:
    external: true
  # https://github.com/BlackOrder/jasmin-core-docker-service
  jasmin-core_rabbitmq_subnet:
    external: true
  # https://github.com/BlackOrder/jasmin-core-docker-service
  jasmin-core_redis_subnet:
    external: true
  # https://github.com/BlackOrder/mongo-cluster
  mongo-cluster_cluster_subnet:
    external: true
